### ISSUE TITLE
Splice Command

### ISSUE THREAD

**Issue by nickalaskreynolds** [nickalaskreynolds/Star-Bot#14]
Splice command unable to place a correct embedded emoji. Error below:

Error:
> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
>	at java.base/java.util.LinkedList.checkElementIndex(LinkedList.java:559)
>	at java.base/java.util.LinkedList.get(LinkedList.java:480)
>	at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1310)
>	at io.ph.bot.commands.general.Slice.executeCommand(Slice.java:57)
>	at 
> io.ph.bot.commands.CommandHandler.lambda$processCommand$0(CommandHandler.java:98)
>	at io.ph.util.Util.lambda$setTimeout$0(Util.java:290)
>	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by nickalaskreynolds** [comment]
cant seem to replicate issue, removing for now
