### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by nickalaskreynolds** [nickalaskreynolds/Star-Bot#15]
Add bot github issue link to the suggest command.

**Comment by nickalaskreynolds** [comment]
Error in suggest command
> java.lang.NullPointerException
> 	at io.ph.bot.commands.general.Suggestion.lambda$executeCommand$1(Suggestion.java:66)
> 	at net.dv8tion.jda.core.requests.RestAction$EmptyRestAction.queue(RestAction.java:771)
> 	at net.dv8tion.jda.core.requests.RestAction.queue(RestAction.java:311)
> 	at io.ph.bot.commands.general.Suggestion.executeCommand(Suggestion.java:63)
> 	at 
> io.ph.bot.commands.CommandHandler.lambda$processCommand$0(CommandHandler.java:98)
> 	at io.ph.util.Util.lambda$setTimeout$0(Util.java:303)

**Comment by nickalaskreynolds** [comment]
the suggest command is messaging the user that sent the command and not the botdev

**Comment by nickalaskreynolds** [comment]
fixed. messages both
