### ISSUE TITLE
Music Errors and upgrades

### ISSUE THREAD

**Issue by nickalaskreynolds** [nickalaskreynolds/Star-Bot#18]
I think either API update or DRM lockout. Certain songs/urls lead to errors
```
!play don't go breakin my heart backstreet boys
!play and so it goes marianas trench
```

**Comment by nickalaskreynolds** [comment]
```
```
[lava-daemon-pool-playback-1-thread-1] ERROR com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Error in playback of aJOTlE1K90k
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.IllegalStateException: Must find action functions from script: /yts/jsbin/player-vflM-t6FF/en_US/base.js
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.extractTokensFromScript(YoutubeSignatureCipherManager.java:185)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:141)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getValidUrl(YoutubeSignatureCipherManager.java:100)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:99)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:60)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
	... 4 more
[JDA AudioConnection Guild: 97886936382853120 Sending Thread] ERROR com.sedmelluq.discord.lavaplayer.player.AudioPlayer - Handler of event com.sedmelluq.discord.lavaplayer.player.event.TrackEndEvent@3973dd17 threw an exception.
java.lang.IllegalStateException: java.lang.InterruptedException
	at net.dv8tion.jda.core.utils.MiscUtil.locked(MiscUtil.java:244)
	at net.dv8tion.jda.core.audio.AudioWebSocket.locked(AudioWebSocket.java:422)
	at net.dv8tion.jda.core.audio.AudioWebSocket.close(AudioWebSocket.java:446)
	at net.dv8tion.jda.core.audio.AudioConnection.close(AudioConnection.java:231)
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.lambda$closeAudioConnection$0(AudioManagerImpl.java:148)
	at net.dv8tion.jda.core.utils.MiscUtil.locked(MiscUtil.java:240)
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.closeAudioConnection(AudioManagerImpl.java:144)
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.closeAudioConnection(AudioManagerImpl.java:139)
	at io.ph.bot.audio.GuildTrackManager.onTrackEnd(GuildTrackManager.java:84)
	at com.sedmelluq.discord.lavaplayer.player.event.AudioEventAdapter.onEvent(AudioEventAdapter.java:70)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.dispatchEvent(AudioPlayer.java:295)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.handleTerminator(AudioPlayer.java:217)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provideDirectly(AudioPlayer.java:197)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provide(AudioPlayer.java:167)
	at com.sedmelluq.discord.lavaplayer.track.playback.AudioFrameProviderTools.delegateToTimedProvide(AudioFrameProviderTools.java:18)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provide(AudioPlayer.java:162)
	at io.ph.bot.audio.AudioPlayerSendHandler.canProvide(AudioPlayerSendHandler.java:26)
	at net.dv8tion.jda.core.audio.AudioConnection$PacketProvider.getNextPacketRaw(AudioConnection.java:641)
	at net.dv8tion.jda.core.audio.AudioConnection$PacketProvider.getNextPacket(AudioConnection.java:631)
	at net.dv8tion.jda.core.audio.factory.DefaultSendSystem.lambda$start$0(DefaultSendSystem.java:69)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1247)
	at java.base/java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:317)
	at net.dv8tion.jda.core.utils.MiscUtil.locked(MiscUtil.java:239)
```
```

**Comment by nickalaskreynolds** [comment]
```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.IllegalStateException: Must find action functions from script: /yts/jsbin/player-vflM-t6FF/en_US/base.js
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.extractTokensFromScript(YoutubeSignatureCipherManager.java:185)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:141)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getValidUrl(YoutubeSignatureCipherManager.java:100)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:99)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:60)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
	... 4 more
[JDA AudioConnection Guild: 97886936382853120 Sending Thread] ERROR com.sedmelluq.discord.lavaplayer.player.AudioPlayer - Handler of event com.sedmelluq.discord.lavaplayer.player.event.TrackEndEvent@729ec98f threw an exception.
java.lang.IllegalStateException: java.lang.InterruptedException
	at net.dv8tion.jda.core.utils.MiscUtil.locked(MiscUtil.java:244)
	at net.dv8tion.jda.core.audio.AudioWebSocket.locked(AudioWebSocket.java:422)
	at net.dv8tion.jda.core.audio.AudioWebSocket.close(AudioWebSocket.java:446)
	at net.dv8tion.jda.core.audio.AudioConnection.close(AudioConnection.java:231)
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.lambda$closeAudioConnection$0(AudioManagerImpl.java:148)
	at net.dv8tion.jda.core.utils.MiscUtil.locked(MiscUtil.java:240)
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.closeAudioConnection(AudioManagerImpl.java:144)
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.closeAudioConnection(AudioManagerImpl.java:139)
	at io.ph.bot.audio.GuildTrackManager.onTrackEnd(GuildTrackManager.java:84)
	at com.sedmelluq.discord.lavaplayer.player.event.AudioEventAdapter.onEvent(AudioEventAdapter.java:70)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.dispatchEvent(AudioPlayer.java:295)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.handleTerminator(AudioPlayer.java:217)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provideDirectly(AudioPlayer.java:197)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provide(AudioPlayer.java:167)
	at com.sedmelluq.discord.lavaplayer.track.playback.AudioFrameProviderTools.delegateToTimedProvide(AudioFrameProviderTools.java:18)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provide(AudioPlayer.java:162)
	at io.ph.bot.audio.AudioPlayerSendHandler.canProvide(AudioPlayerSendHandler.java:26)
	at net.dv8tion.jda.core.audio.AudioConnection$PacketProvider.getNextPacketRaw(AudioConnection.java:641)
	at net.dv8tion.jda.core.audio.AudioConnection$PacketProvider.getNextPacket(AudioConnection.java:631)
	at net.dv8tion.jda.core.audio.factory.DefaultSendSystem.lambda$start$0(DefaultSendSystem.java:69)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1247)
	at java.base/java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:317)
	at net.dv8tion.jda.core.utils.MiscUtil.locked(MiscUtil.java:239)
	... 20 more
```

**Comment by nickalaskreynolds** [comment]
further testing and it does seem to be DRM. Songs from some official channels dont work while finding an unofficial works. Will need further testing

**Comment by nickalaskreynolds** [comment]
**A new error occured for just a few urls. Not sure why this is caused but know the issue**

> [lava-daemon-pool-playback-1-thread-111] ERROR com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Error in playback of 90wySZfZcwY

> Exception in thread "lava-daemon-pool-playback-1-thread-111" java.lang.UnsatisfiedLinkError: /tmp/lava-jni-natives/1535075900054/libconnector.so: libstdc++.so.6: cannot open shared object file: No such file or directory

**Comment by nickalaskreynolds** [comment]
Was exactly missing ` libstdc++.so.6: ` so just added it to the LDLIBRARYPATH and works...
