### ISSUE TITLE
remindme

### ISSUE THREAD

**Issue by nickalaskreynolds** [nickalaskreynolds/Star-Bot#2]
For some reason the remindme isnt working properly. Regardless of time and format will send a notification asap (about 1s).

**Comment by nickalaskreynolds** [comment]
Need to correct his and allow the function to be more portable. Just keep track of

**Comment by nickalaskreynolds** [comment]
```
ERROR org.quartz.core.ErrorLogger - Job (group1.reminderJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
	at org.sqlite.core.NativeDB._open_utf8(Native Method)
	at org.sqlite.core.NativeDB._open(NativeDB.java:71)
	at org.sqlite.core.DB.open(DB.java:174)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:26)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:678)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at io.ph.db.ConnectionPool.getGlobalDatabaseConnection(ConnectionPool.java:17)
	at io.ph.bot.jobs.ReminderJob.execute(ReminderJob.java:39)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
```
