### ISSUE TITLE
Message Deletion

### ISSUE THREAD

**Issue by nickalaskreynolds** [nickalaskreynolds/Star-Bot#21]
Where it deletes the message, have it now wait 5 seconds and then delete it.

Commands to apply this to:
> help : both command and response for DM, command for in channel message
> macro : command
> quote : command
> prune : command and responce
> power : both command and response for DM, command for in channel message

**Comment by nickalaskreynolds** [comment]
java.lang.IndexOutOfBoundsException: Index 0 out-of-bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:440)
	at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1310)
	at io.ph.util.MessageUtils.sendMessage(MessageUtils.java:53)
	at io.ph.bot.commands.moderation.Prune.lambda$executeCommand$4(Prune.java:84)
	at net.dv8tion.jda.core.requests.Request.lambda$onSuccess$0(Request.java:72)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:299)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at net.dv8tion.jda.core.entities.impl.JDAImpl$JDAThreadFactory.lambda$newThread$0(JDAImpl.java:750)

**Comment by nickalaskreynolds** [comment]
completed

**Comment by nickalaskreynolds** [comment]
need to update the prune command to delete user message

**Comment by nickalaskreynolds** [comment]
> quote list user

This deletes after 5 seconds. Change this
