### ISSUE TITLE
clearchat command

### ISSUE THREAD

**Issue by nickalaskreynolds** [nickalaskreynolds/Star-Bot#25]
command to clear an entire text channel

**Comment by nickalaskreynolds** [comment]
m.getAuthor().getId(): 477182646925918214
botIDlong: 477182646925918214
em: net.dv8tion.jda.core.entities.MessageEmbed@5cbb501
java.lang.IndexOutOfBoundsException: Index 0 out-of-bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:440)
	at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1310)
	at io.ph.util.MessageUtils.sendMessage(MessageUtils.java:53)
	at io.ph.bot.commands.moderation.ClearChat.executeCommand(ClearChat.java:49)
	at io.ph.bot.commands.CommandHandler.lambda$processCommand$1(CommandHandler.java:111)
	at io.ph.util.Util.lambda$setTimeout$1(Util.java:356)
	at java.base/java.lang.Thread.run(Thread.java:844)
[Thread-24] ERROR io.ph.bot.audio.stream.listenmoe.ListenMoeSocke

**Comment by nickalaskreynolds** [comment]
completed
