### ISSUE TITLE
Strawpoll Error

### ISSUE THREAD

**Issue by nickalaskreynolds** [nickalaskreynolds/Star-Bot#30]
Something wrong with the strawpoll
It will go properly though all step functions but then exits without serving the link on the last step `type finish to finish`

**Comment by nickalaskreynolds** [comment]
[JDA MainWS-ReadThread] ERROR net.dv8tion.jda.core.JDA - One of the EventListeners had an uncaught exception
org.json.JSONException: JSONObject["id"] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at org.json.JSONObject.getInt(JSONObject.java:598)
	at io.ph.bot.model.StrawpollObject.createPoll(StrawpollObject.java:56)
	at io.ph.bot.commands.moderation.Strawpoll.finish(Strawpoll.java:82)
	at io.ph.bot.commands.moderation.Strawpoll.step(Strawpoll.java:60)
	at io.ph.bot.procedural.ProceduralListener.update(ProceduralListener.java:31)
	at io.ph.bot.listeners.Listeners.onGuildMessageReceived(Listeners.java:304)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:379)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:90)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:1051)
	at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:911)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:890)
	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1089)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by nickalaskreynolds** [comment]
strawpoll api disabled

![2018-08-22-024457_1268x728_scrot](https://user-images.githubusercontent.com/25838944/44439670-38b11780-a58a-11e8-88ee-41989b20170f.png)
