### ISSUE TITLE
roll with mods

### ISSUE THREAD

**Issue by nickalaskreynolds** [nickalaskreynolds/Star-Bot#32]
Allow for modifiers to rolls
> roll 1d12+5
> roll 1d12-5

**Comment by nickalaskreynolds** [comment]
```
isEmojiStatus: :false:
passed emoji logic
java.util.regex.PatternSyntaxException: Dangling meta character '+' near index 0
+
^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2010)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2185)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2051)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1773)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1422)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1082)
	at java.base/java.lang.String.split(String.java:2319)
	at java.base/java.lang.String.split(String.java:2366)
	at io.ph.bot.commands.fun.Roll.executeCommand(Roll.java:47)
	at io.ph.bot.commands.CommandHandler.lambda$processCommand$0(CommandHandler.java:99)
	at io.ph.util.Util.lambda$setTimeout$1(Util.java:568)
	at java.base/java.lang.Thread.run(Thread.java:844)

```

**Comment by nickalaskreynolds** [comment]
completed
