### ISSUE TITLE
Misc issue

### ISSUE THREAD

**Issue by nickalaskreynolds** [nickalaskreynolds/Star-Bot#34]
On startup sometimes this error occurs. cannot always replicate.

```
Exception: 
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
	at org.sqlite.core.NativeDB._open_utf8(Native Method)
	at org.sqlite.core.NativeDB._open(NativeDB.java:71)
	at org.sqlite.core.DB.open(DB.java:174)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:26)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:678)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at io.ph.db.ConnectionPool.getGlobalDatabaseConnection(ConnectionPool.java:17)
	at io.ph.bot.jobs.ReminderJob.execute(ReminderJob.java:39)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[QuartzScheduler_Worker-3] ERROR org.quartz.core.ErrorLogger - Job (group1.reminderJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
	at org.sqlite.core.NativeDB._open_utf8(Native Method)
	at org.sqlite.core.NativeDB._open(NativeDB.java:71)
	at org.sqlite.core.DB.open(DB.java:174)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:26)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:678)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at io.ph.db.ConnectionPool.getGlobalDatabaseConnection(ConnectionPool.java:17)
	at io.ph.bot.jobs.ReminderJob.execute(ReminderJob.java:39)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)

```

**Comment by nickalaskreynolds** [comment]
Another error. Bot doesn't leave after music ends:
```
[JDA AudioConnection Guild: 238853110095806464 Sending Thread] ERROR com.sedmelluq.discord.lavaplayer.player.AudioPlayer - Handler of event com.sedmelluq.discord.lavaplayer.player.event.TrackEndEvent@2a79895c threw an exception.
java.lang.IllegalStateException: java.lang.InterruptedException
	at net.dv8tion.jda.core.utils.MiscUtil.locked(MiscUtil.java:244)
	at net.dv8tion.jda.core.audio.AudioWebSocket.locked(AudioWebSocket.java:422)
	at net.dv8tion.jda.core.audio.AudioWebSocket.close(AudioWebSocket.java:446)
	at net.dv8tion.jda.core.audio.AudioConnection.close(AudioConnection.java:231)
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.lambda$closeAudioConnection$0(AudioManagerImpl.java:148)
	at net.dv8tion.jda.core.utils.MiscUtil.locked(MiscUtil.java:240)
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.closeAudioConnection(AudioManagerImpl.java:144)
	at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.closeAudioConnection(AudioManagerImpl.java:139)
	at io.ph.bot.audio.GuildTrackManager.onTrackEnd(GuildTrackManager.java:84)
	at com.sedmelluq.discord.lavaplayer.player.event.AudioEventAdapter.onEvent(AudioEventAdapter.java:70)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.dispatchEvent(AudioPlayer.java:350)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.handleTerminator(AudioPlayer.java:260)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provide(AudioPlayer.java:196)
	at com.sedmelluq.discord.lavaplayer.track.playback.AudioFrameProviderTools.delegateToTimedProvide(AudioFrameProviderTools.java:18)
	at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provide(AudioPlayer.java:175)
	at io.ph.bot.audio.AudioPlayerSendHandler.canProvide(AudioPlayerSendHandler.java:30)
	at net.dv8tion.jda.core.audio.AudioConnection$PacketProvider.getNextPacketRaw(AudioConnection.java:641)
	at net.dv8tion.jda.core.audio.AudioConnection$PacketProvider.getNextPacket(AudioConnection.java:631)
	at net.dv8tion.jda.core.audio.factory.DefaultSendSystem.lambda$start$0(DefaultSendSystem.java:69)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1247)
	at java.base/java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:317)
	at net.dv8tion.jda.core.utils.MiscUtil.locked(MiscUtil.java:239)
	... 19 more

```

**Comment by nickalaskreynolds** [comment]
Removing music portion of bot. First comment was fixed via fixing permissions of db files to read and write
