### ISSUE TITLE
Problems with the bot

### ISSUE THREAD

**Issue by nickalaskreynolds** [nickalaskreynolds/Star-Bot#37]
Bot plays the first thing called. then adds 624 minutes to the time and doesn't play any other song.

```
16563] INFO io.ph.bot.audio.stream.listenmoe.ListenMoeSocket - Attempting reconnect to Listen.moe socket
passed emoji logic
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:151)
	at io.ph.bot.commands.moderation.Summon.executeCommand(Summon.java:64)
	at io.ph.bot.commands.CommandHandler.lambda$processCommand$0(CommandHandler.java:99)
	at io.ph.util.Util.lambda$setTimeout$1(Util.java:578)
	at java.base/java.lang.Thread.run(Thread.java:844)
[Thread-16569] ERROR io.ph.bot.audio.stream.listenmoe.ListenMoeSocket - Listen.moe socket closed: -1: draft org.java_websocket.drafts.Draft_6455@596aa2bf refuses handshake
```

**Comment by nickalaskreynolds** [comment]
Removed the listen.moe and will eventually remove all music from this bot
