### ISSUE TITLE
Moderation 

### ISSUE THREAD

**Issue by nickalaskreynolds** [nickalaskreynolds/Star-Bot#6]
This is a little harder since current functionality conflicts. Allow users to whisper the bot for mods or botdev in case of abuse, respectively:
> report guildID: reportform stuff here
> report  reportform stuff here
Also allow the kick,ban to apply to people both in and not in the server

**Comment by nickalaskreynolds** [comment]
add ability to move people to certain VC or remote them from VC

**Comment by nickalaskreynolds** [comment]
```
java.lang.NullPointerException
	at io.ph.util.MessageUtils.sendMessage(MessageUtils.java:49)
	at io.ph.util.MessageUtils.sendMessage(MessageUtils.java:24)
	at io.ph.bot.listeners.Listeners.onPrivateMessageReceived(Listeners.java:357)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:395)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:100)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:1051)
	at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:911)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:890)
	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1089)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

```

**Comment by nickalaskreynolds** [comment]
completed

**Comment by nickalaskreynolds** [comment]
for the report function. Check if there is the report channel. Else send to build owner
